apps/cities/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # URL pattern for the HomeView
    path(
        route = '',
        view = views.HomeView,
        name = 'home',
    ),

    path(
        route = 'select/',
        view = views.SelectView,
        name = 'select',
    ),    

    path(
        route = 'selection/<int:city_id>',
        view = views.SelectionView,
        name = 'selection',
    ),    

    # ajax
    path(
        route = 'ajax/load-regions/',
        view = views.load_regions,
        name = 'ajax_load_regions',
    ),
    path(
        route = 'ajax/load-cities/',
        view = views.load_cities,
        name = 'ajax_load_cities',
    ),
]

apps/homepage/urls.py
#from django.conf.urls import url 
from django.urls import path
 
from . import views 
 
urlpatterns = [ 
    # url( 
    #     regex='^$', 
    #     view=views.HomeView, 
    #     name='home' 
    # ), 
    path( 
        route='', 
        view=views.HomeView, 
        name='home' 
    ),     
] 

config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.views import defaults as default_views


urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),

    # Homepage app
    path('', include('homepage.urls')),

    # django-allauth
    path('accounts/', include('allauth.urls')), 

    path('cities/', include(('cities.urls', 'cities'), namespace='cities')),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

apps/cities/models.py
from django.db import models 
 
from cities_light.abstract_models import AbstractCity, AbstractRegion, AbstractCountry
from cities_light.receivers import connect_default_signals

#import uuid


class Country(AbstractCountry):
    #id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    pass
connect_default_signals(Country)

class Region(AbstractRegion):
    #id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    pass
connect_default_signals(Region)

class City(AbstractCity):
    #id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    timezone = models.CharField(max_length=40)
connect_default_signals(City)

apps/homepage/models.py
from django.db import models 
 
# Create your models here. 

apps/cities/forms.py
from django import forms

from cities.models import City, Region

class CityForm(forms.ModelForm):
    """
    """
    class Meta:
        model = City
        fields = (
            'country',
            'region',
            'name', 
        )
        labels = {
            'name': 'City'
        }
        widgets = {
            'name': forms.Select
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['region'].queryset = Region.objects.none()
        self.fields['name'].queryset = City.objects.none()

        if 'country' in self.data:
            try:
                country_id = int(self.data.get('country'))
                self.fields['region'].queryset = Region.objects.filter(country_id=country_id).order_by('name')
            except (ValueError, TypeError):
                pass # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['region'].queryset = self.instance.country.region_set.order_by('name')

apps/cities/views.py
from django.shortcuts import render
from django.shortcuts import redirect

from cities.models import Region, City
from cities.forms import CityForm

def HomeView(request):
    """
    """
    context = {}
    return render(request, 'cities/home.html', context) 

def SelectionView(request, city_id):
    """
    """
    city = City.objects.get( pk = city_id)
    print(city)
    context = {'city': city}
    return render(request, 'cities/selection.html', context)     

def SelectView(request):
    """
    """

    if request.method == "POST":
        city_form = CityForm(request.POST)
        if city_form.is_valid():
            print(dir(city_form))
            print(city_form.data)
            return redirect('cities:selection', city_id = city_form.data['name'])
            #context = {'city_id': city_form.data['name']}
            #return render(request, 'cities/selection.html', context)
    else:
        city_form = CityForm()
    context = {
        'form': city_form
    }
    return render(request, 'cities/select.html', context)

# ----------------
# chained dropdwon 

def load_regions(request):
    """
    filter regions for selected country
    """
    country_id = request.GET.get('country')
    regions = Region.objects.filter(country_id=country_id)
    return render(request, 'cities/region_dropdown_list_options.html', {'regions': regions})

def load_cities(request):
    """
    filter cities for selected country/region
    """
    region_id = request.GET.get('region')
    cities = City.objects.filter(region_id=region_id)
    return render(request, 'cities/city_dropdown_list_options.html', {'cities': cities})

# /chained dropdwon
# ----------------

apps/homepage/views.py
from django.shortcuts import render 
 
def HomeView(request): 
    """ 
    """ 
 
    context = {} 
    return render(request, 'homepage/home.html', context)

apps/cities/templates/cities/base.html
{% extends "base.html" %}

{% block title %}Cities{% endblock title %}

apps/cities/templates/cities/city_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

apps/cities/templates/cities/home.html
{% extends "cities/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
	<h1>Cities app</h1>
{% endblock content %}

apps/cities/templates/cities/region_dropdown_list_options.html
<option value="">---------</option>
{% for region in regions %}
<option value="{{ region.pk }}">{{ region.name }}</option>
{% endfor %}

apps/cities/templates/cities/select.html
{% extends "cities/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
	<h2>select a city</h2>

	<p>inspired by 
		<a href="https://simpleisbetterthancomplex.com/tutorial/2018/01/29/how-to-implement-dependent-or-chained-dropdown-list-with-django.html">
			How to Implement Dependent/Chained Dropdown List with Django
		</a>
	</p>

	<form method="post" id="cityForm" data-regions-url="{% url 'cities:ajax_load_regions' %}" data-cities-url="{% url 'cities:ajax_load_cities' %}" novalidate>
		{% csrf_token %}
		<table>
		  {{ form.as_table }}
		</table>
		<button type="submit">Save</button>
		<a href="{% url 'cities:home' %}">Nevermind</a>
	</form>



{% endblock content %}

{% block javascript-app %}
<script>
	$("#id_country").change(function () {
		console.log('cliccato COUNTRY') // DEBUG
 		var url = $("#cityForm").attr("data-regions-url");  // get the url of the `load_regions` view
		//console.log(url)	// DEBUG
	    var countryId = $(this).val();  // get the selected country ID from the HTML input
		//console.log(countryId) //DEBUG
	  	$.ajax({                       // initialize an AJAX request
			url: url,                    // set the url of the request (= localhost:8000/cities/ajax/load-regions/)
			data: {
		  		'country': countryId       // add the country id to the GET parameters
			},
			success: function (data) {   // `data` is the return of the `load_regions` view function
				//console.log(data) // DEBUG
		  		$("#id_region").html(data);  // replace the contents of the city input with the data that came from the server
			}
	  	});
	}); 
</script>
<script>
	$("#id_region").change(function () {
		console.log('cliccato REGION') // DEBUG
 		var url = $("#cityForm").attr("data-cities-url");  // get the url of the `load_regions` view
		//console.log(url)	// DEBUG
	    var regionId = $(this).val();  // get the selected country ID from the HTML input
		//console.log(regionId) //DEBUG
	  	$.ajax({                       // initialize an AJAX request
			url: url,                    // set the url of the request (= localhost:8000/cities/ajax/load-regions/)
			data: {
		  		'region': regionId       // add the country id to the GET parameters
			},
			success: function (data) {   // `data` is the return of the `load_regions` view function
				//console.log(data) // DEBUG
		  		$("#id_name").html(data);  // replace the contents of the city input with the data that came from the server
			}
	  	});
	}); 
</script>
{% endblock javascript-app %}

apps/cities/templates/cities/selection.html
{% extends "cities/base.html" %}

{% block title %}selection{% endblock %}

{% block content %}
	<h2>your selection</h2>


	{{ city.name }}
	{{ city.region.name }}
	{{ city.country }}


{% endblock content %}

apps/homepage/templates/homepage/home.html
{% extends "base.html" %}

{% block content %}
<h1> Homepage </h1>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
{% endblock %}

demo_cities/templates/asia/base.html
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>{% block title %}demo Cities{% endblock title %}</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- /Bootstrap -->

    {% load static%}
    <link href="{% static 'asia/css/styles.css' %}" rel="stylesheet">    

</head>

<body>

    <div class="wrapper">
        {% block sidebar %}
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3>Bootstrap Sidebar</h3>
                <strong>BS</strong>
            </div>
    
            <ul class="list-unstyled components">
                <li class="active">
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <i class="fas fa-home"></i>
                        Home
                    </a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            <a href="#">Home 1</a>
                        </li>
                        <li>
                            <a href="#">Home 2</a>
                        </li>
                        <li>
                            <a href="#">Home 3</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-briefcase"></i>
                        About
                    </a>
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <i class="fas fa-copy"></i>
                        Pages
                    </a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            <a href="#">Page 1</a>
                        </li>
                        <li>
                            <a href="#">Page 2</a>
                        </li>
                        <li>
                            <a href="#">Page 3</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-image"></i>
                        Portfolio
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-question"></i>
                        FAQ
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fas fa-paper-plane"></i>
                        Contact
                    </a>
                </li>
            </ul>
    
            <ul class="list-unstyled CTAs">
                <li>
                    <a href="https://bootstrapious.com/tutorial/files/sidebar.zip" class="download">Download source</a>
                </li>
                <li>
                    <a href="https://bootstrapious.com/p/bootstrap-sidebar" class="article">Back to article</a>
                </li>
            </ul>
        </nav>
        {% endblock sidebar%}
    
        <!-- Page Content  -->
        <div id="content">

            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
    
                    <button type="button" id="sidebarCollapse" class="btn btn-info">
                        <i class="fa fa-bars"></i>
                    </button>
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>
    
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item active">
                                <a class="nav-link" href="#">Page</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Page</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Page</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#">Page</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

            {% block content %}
            {% endblock content%}
        </div>
    </div>    

    <!-- Bootstrap -->
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <!-- /Bootstrap -->

    <!-- Fontawesome -->
    <script defer src="https://use.fontawesome.com/releases/v5.2.0/js/all.js" integrity="sha384-4oV5EgaV02iISL2ban6c/RmotsABqE4yZxZLcYMAdG7FAPsyHYAPpywE9PJo+Khy" crossorigin="anonymous"></script>
    <!-- /Fontawesome -->

    <script type="text/javascript">
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        });
    </script>

      {% block javascript-app %}
      <!-- JavaScript section for apps -->
      {% endblock javascript-app %}

</body>
</html>

demo_cities/templates/base.html
{% extends "asia/base.html" %}